---
- name: Configure firewalld
  block:
    - name: Enable HTTP for firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
