---
- name: Configure firewalld
  block:
    - name: Enable HTTP for firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
    - name: Enable rhcos_cache port for firewalld
      firewalld:
        port: "{{ webserver_caching_port_container }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      become: yes

