---
- name: Setup network manager DNS overlay
  copy:
    dest: /etc/NetworkManager/conf.d/openshift.conf
    content: |
      [main]
      dns=dnsmasq

- name: Restart NetworkManager to apply
  service:
    name: NetworkManager
    state: restarted
