---
- name: Preparation tasks
  block:
    - include_tasks: roles/node-prep/tasks/10_enable_services.yml
    - include_tasks: roles/node-prep/tasks/20_configure_firewall.yml
    - include_tasks: roles/node-prep/tasks/30_configure_libvirt.yml
    - include_tasks: roles/node-prep/tasks/40_create_config_dirs.yml
    - include_tasks: roles/node-prep/tasks/50_configure_dns.yml
      when: virtualized_install|bool
  tags: node_preparation


