additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIGKjCCBBKgAwIBAgIUBSp5rVz968q3mbTLeFAe0Riv+rYwDQYJKoZIhvcNAQEL
  BQAwgYoxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdNeVN0YXRlMQ8wDQYDVQQHDAZN
  eUNpdHkxEjAQBgNVBAoMCU15Q29tcGFueTEVMBMGA1UECwwMTXlEZXBhcnRtZW50
  MS0wKwYDVQQDDCR2aXAudGVzdGluZy5iYXJlbWV0YWwuZWRnZS1zaXRlcy5uZXQw
  HhcNMjAwODIwMTUxMTExWhcNMzAwODE4MTUxMTExWjCBijELMAkGA1UEBhMCVVMx
  EDAOBgNVBAgMB015U3RhdGUxDzANBgNVBAcMBk15Q2l0eTESMBAGA1UECgwJTXlD
  b21wYW55MRUwEwYDVQQLDAxNeURlcGFydG1lbnQxLTArBgNVBAMMJHZpcC50ZXN0
  aW5nLmJhcmVtZXRhbC5lZGdlLXNpdGVzLm5ldDCCAiIwDQYJKoZIhvcNAQEBBQAD
  ggIPADCCAgoCggIBAMpmG7CLLR82iCUWFkYeNmfWqG3VxT7Wxz+wxu7hNWL1dOAq
  E1VlrRGUAMiRehG/43Vd0gqGtPKXOTpIwxXTWIhVFoBIfVFqysrfUR5zLiel745J
  mLm+l2AQs4ketNlIwNwaJXtD0E7I8qgIzmb6BJ9/MNMgzrIcfHVEu1pAb7vE/F5e
  TKJZywYPbXIdu7rPF0dM7dG7XvuCYJhXKAjkDrwhuwR1dVYJNEiZEaOPBa3xGbv7
  NppICLoHPQBiF3i8D+WerCcGLf+BU5vg0mcSKItEjFEXS7ck+eo7a/hkWXL6r8Wy
  mkRrvqGW69RLz2vn+T9BkupGc4I3iY421VixuChYvuk2nIFovVY4/DBbOwTFP79A
  NGqXDbY03QbCX10nlV+qZFzRTSrP7K03Fjrr+fFnAZNQK2Vkev/NxrTt8U3ZlizR
  LjBPJrET9aQd0t7DxG+tyPcIJ9wYbgY6PfdBfIXHwCgre6fNEDrfj73jXSQRHXjK
  +O2+wMcy4FVhLS1lO6YqdVmiC1HRDHaPLCF51PhXCfZxe7GMQWvqwB4P/1uQrMvT
  pgdsg0Ovxjr8h1CABcDO4HNxEgr7eI/B+DpBsUDwLvEUWNfc/EjJ7GkDvnRXHcMk
  JPlFKWleDmJtogGFt3HYaB4s1kTeys9dp/TKzSSuop24IQBpI1ZpKznaAF5hAgMB
  AAGjgYUwgYIwLwYDVR0RBCgwJoIkdmlwLnRlc3RpbmcuYmFyZW1ldGFsLmVkZ2Ut
  c2l0ZXMubmV0MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBmzi5z5HGvYdQ4J
  T9GA7cbSvJsBMB8GA1UdIwQYMBaAFBmzi5z5HGvYdQ4JT9GA7cbSvJsBMA0GCSqG
  SIb3DQEBCwUAA4ICAQAXw+OV7jYs/+vAkXFMBpIweiQfbBfC8NpXc/WyFVcThb3m
  OfbrvdNs8Wnq1A1YDXP0jk8nd6iyJwWsRimd2TltNOwonxS7tEN67PneZRSC7hkb
  GNNo9FGJcR4WydhXtTWGocpljypGELc26ObCrjUb4CJIp7G9p6y7XERpYjsK7/68
  tO251WtmwO8hy5C0TNdU01MzWjNrX+YtayM73vCItI55YfIaHiThGUFMVmdKUrWq
  KnVI1Rynu2kmzbg5Drmo+io4hEHM4ax3umbVA0NjXMNVsE86Ah9qud5JrR6gx5kj
  /sgB+JEts7GqF3k36a2yE7dbJnxLbGUhTA3PKwrUUxOsvbjPn3HOoA9p5tS51tqv
  U60EjWb262zxX8GXgSqVQ8VXeg1U3qgRMJZjnFAz1M6Hds78F2t6OYWlVJxqtgoc
  aoSNxZbKYitQ4/8QqPizUgZCnYUqg7Xtq8lhI0C0vqHoxHwKgkxwOlFERJGjBAic
  0DbZ8KO9634r2JQtAJ4Q93Oa4HRrj+RkuIP8d0jJ2RCtcagAr09cEJmRM4m6wIPE
  VRXYNJdQMdO6TKkG1OdiO+Zu81cK33vBsWjLrJO0cZfDWdJGoAIm0oqAvrmIkhqA
  /nlRDWa/bUmqhrkNy1QD0vZEwWKa8XZ5+KKqJPk/W31RYBrMyruule35hjzNSA==
  -----END CERTIFICATE-----
  
imageContentSources:
- mirrors:
  - vip.testing.baremetal.edge-sites.net:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - vip.testing.baremetal.edge-sites.net:5000/ocp4/openshift4
  source: registry.svc.ci.openshift.org/ocp/release
- mirrors:
  - vip.testing.baremetal.edge-sites.net:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
