---
- name: Get list of all VMs
  virt:
    command: list_vms
  register: all_vms
  become: yes

- name: Get list of all running VMs
  virt:
    command: list_vms
    state: running
  register: running_vms
  become: yes

- name: Destroy old master/worker VMs, if any
  virt:
    name: "{{ item }}"
    command: destroy
  with_items: "{{ running_vms.list_vms }}"
  when: item is search("master") or item is search("worker")
  become: yes

- name: Undefine old master/worker VMs, if any
  virt:
    name: "{{ item }}"
    command: undefine
  with_items: "{{ all_vms.list_vms }}"
  when: item is search("master") or item is search("worker")
  become: yes

- name: Find old master VM Storage
  find:
    paths: "{{ default_libvirt_pool_dir }}"
    patterns: '*-master,*-master.ign'
  register: find_results
  become: yes

- name: Delete old master VMs Storage
  file:
    path: "{{ item['path'] }}"
    state: absent
  loop: "{{ find_results['files'] }}"
  become: yes

- name: Find old worker VM Storage
  find:
    paths: "{{ default_libvirt_pool_dir }}"
    patterns: '*-worker,*-worker.ign'
  register: find_results
  become: yes

- name: Delete old worker VMs Storage
  file:
    path: "{{ item['path'] }}"
    state: absent
  loop: "{{ find_results['files'] }}"
  become: yes

- name: Delete old baremetal network
  virt_net:
    command: destroy
    name: baremetal-{{ cluster }}
  ignore_errors: true
  become: yes

- name: Undefine old baremetal network
  virt_net:
    command: undefine
    name: baremetal-{{ cluster }}
  ignore_errors: true
  become: yes
