---
- name: Start installation process
  block:
    - include_tasks: roles/installer/tasks/clean_bootstrap_vm.yml
    - include_tasks: roles/installer/tasks/clean_master_worker_vms.yml
      when: virtualized_install
  tags: installer
