---
- name: Start installation process
  block:
    - include_tasks: roles/installer/tasks/10_clean_bootstrap_vm.yml
    - include_tasks: roles/installer/tasks/20_clean_master_worker_vms.yml
      when: virtualized_install
    - include_tasks: roles/installer/tasks/30_create_bootstrap_vm.yml
  tags: installer
