---
- name: Create OpenShift Manifest
  shell: |
    /usr/local/bin/openshift-baremetal-install --dir {{ cluster_config_dir }} create manifests
  tags: manifests

- name: Ensure the manifests dir is owned by {{ ansible_user }}
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
  - "{{ cluster_config_dir }}/openshift"
  - "{{ cluster_config_dir }}/manifests"

- name: Add Manifests from files dir
  copy:
    src: "{{ item }}"
    dest: "{{ cluster_config_dir }}/openshift/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_fileglob:
    - files/manifests/*

- name: Manage chrony configuration
  block:
  - name: Create chrony.conf
    set_fact:
      chronyconfig: "{{ lookup('template', 'chrony.conf.j2') | b64encode }}"

  - name: Inject chrony.conf in a machine-config object
    template:
      src: etc-chrony.conf.j2
      dest: "{{ dir }}/openshift/98-{{ item }}-etc-chrony.conf.yaml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    with_items:
      - master
      - worker
  when: (clock_servers is defined) and (clock_servers | length > 0)
